version: 2
updates:
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"
    assignees:
      - "Shi-Raida"
    reviewers:
      - "Shi-Raida"
    
  # Enable version updates for npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"
    assignees:
      - "Shi-Raida"
    reviewers:
      - "Shi-Raida"
    ignore:
      # Ignore major version updates for semantic-release to avoid breaking changes
      - dependency-name: "semantic-release"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@semantic-release/*"
        update-types: ["version-update:semver-major"]