---
stages:
  - Static Analysis
  - Release

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - .venv

default:
  image: node:latest
  interruptible: true

.python-job:
  image: python:latest
  before_script:
    - python --version ; pip --version
    - pip install virtualenv
    - virtualenv .venv
    - source .venv/bin/activate
    - pip install ansible ansible-lint

# ============================================================================ #
#                                Static Analysis                               #
# ============================================================================ #

ansible-lint:
  extends: .python-job
  stage: Static Analysis
  allow_failure: true
  script:
    - ansible-lint --exclude .venv

commitlint:
  stage: Static Analysis
  image: node:latest
  before_script:
    - npm install --save-dev @commitlint/cli @commitlint/config-conventional
  script:
    - npx commitlint --from ${CI_MERGE_REQUEST_TARGET_BRANCH_SHA} --to HEAD --verbose

# ============================================================================ #
#                                    Release                                   #
# ============================================================================ #

semantic-release:
  stage: Release
  image: node:latest
  before_script:
    - npm install --save-dev conventional-changelog-conventionalcommits semantic-release @semantic-release/changelog @semantic-release/exec @semantic-release/git @semantic-release/gitlab-config
  script:
    - npx semantic-release
