---
- hosts: localhost
  connection: local

  vars_files:
    - vars/main.yml

  handlers:
    - import_tasks: handlers/main.yml

  tasks:
    - import_tasks: "{{ tasks_file }}"
      environment: "{{ env }}"
