- name: Install/Upgrade Ansible with python3-venv
  ansible.builtin.pip:
    name: ansible
    state: present
    virtualenv: "{{ opt_dir }}/ansible"
    virtualenv_command: python3 -m venv
  become: true
  # ansible-lint: ignore package-latest
  # Using latest is acceptable for development tools like Ansible

- name: Create Ansible symlink
  ansible.builtin.file:
    src: "{{ item }}"
    dest: "{{ bin_dir }}/{{ item | basename }}"
    state: link
  with_fileglob: "{{ opt_dir }}/ansible/bin/ansible*"
  become: true

- name: Remove Ansible apt package
  ansible.builtin.apt:
    name: ansible
    state: absent
    purge: true
  become: true
  when: ansible_python.executable == opt_dir ~ '/ansible/bin/python3'
