---
- name: Update apt cache and upgrade system
  apt:
    upgrade: safe
    update_cache: true
  become: true
  register: apt_upgrade
  notify: Print apt upgrade info

- import_tasks: handlers/apt_upgrade.yml

- name: Install packages from apt
  apt:
    name: "{{ item }}"
  become: true
  with_items: "{{ apt_packages }}"

- name: Install screen dependent packages from apt
  apt:
    name: "{{ item }}"
  become: true
  when: ansible_env.DISPLAY is defined
  with_items: "{{ apt_screen_packages }}"

- name: Remove old apt dependencies
  apt:
    autoremove: yes
  become: true

- name: Clean old apt packages cache
  apt:
    autoclean: true
  become: true
