---
- name: Update apt cache and upgrade system
  ansible.builtin.apt:
    upgrade: safe
    update_cache: true
  become: true
  register: apt_upgrade
  notify: Print apt upgrade info

- ansible.builtin.import_tasks: handlers/apt_upgrade.yml
- name: Install packages from apt
  ansible.builtin.apt:
    name: "{{ item }}"
  become: true
  with_items: "{{ apt_packages }}"

- name: Install screen dependent packages from apt
  ansible.builtin.apt:
    name: "{{ item }}"
  become: true
  when: ansible_env.DISPLAY is defined
  with_items: "{{ apt_screen_packages }}"

- name: Remove old apt dependencies
  ansible.builtin.apt:
    autoremove: true
  become: true

- name: Clean old apt packages cache
  ansible.builtin.apt:
    autoclean: true
  become: true
