---
- name: Install fonts
  ansible.builtin.apt:
    name: "{{ item }}"
  become: true
  with_items: "{{ fonts }}"

- name: Create nerdfonts directories
  ansible.builtin.file:
    path: "{{ xdg_data_home }}/fonts/{{ item }}NerdFont/"
    state: directory
  with_items: "{{ nerdfonts }}"

- name: Download and extract nerdfonts
  ansible.builtin.unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/latest/download/{{ item }}.zip
    dest: "{{ xdg_data_home }}/fonts/{{ item }}NerdFont/"
    remote_src: true
  with_items: "{{ nerdfonts }}"
