---
- name: Install fonts
  apt:
    name: "{{ item }}"
  become: true
  with_items: "{{ fonts }}"

- name: Create nerdfonts directories
  file:
    path: "{{ xdg_data_home }}/fonts/{{ item }}NerdFont/"
    state: directory
  with_items: "{{ nerdfonts }}"

- name: Download and extract nerdfonts
  unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/latest/download/{{ item }}.zip
    dest: "{{ xdg_data_home }}/fonts/{{ item }}NerdFont/"
    remote_src: yes
  with_items: "{{ nerdfonts }}"
