---
- name: Install git package
  ansible.builtin.apt:
    name: git
  become: true

- name: Install diff-so-fancy
  ansible.builtin.git:
    repo: https://github.com/so-fancy/diff-so-fancy.git
    dest: "{{ opt_dir }}/diff-so-fancy/"
    version: "{{ diff_so_fancy_version | default('HEAD') }}"

- name: Copy git config
  ansible.builtin.template:
    src: git/gitconfig.j2
    dest: "{{ ansible_user_dir }}/.gitconfig"
  vars:
    email: "{{ git_email }}"
    name: "{{ git_name }}"
