---
- name: If run in X.org
  when: ansible_env.DISPLAY is defined
  block:
    - name: Install i3 packages
      ansible.builtin.apt:
        name: "{{ item }}"
      become: true
      with_items:
        - i3-wm
        - i3lock-fancy
        - dunst
        - polybar
        - rofi
        - brightnessctl
        - feh
        - numlockx
        - unclutter
        - xdotool
        - xinit

    - name: Setup i3 volume controls
      ansible.builtin.import_tasks: i3-volume.yml
    - name: Setup bluetooth integration
      ansible.builtin.import_tasks: bluetooth.yml
    - name: Copy config files
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ xdg_config_home }}/"
      with_items:
        - i3
        - dunst
        - polybar
        - rofi

    - name: Make config file scripts executable
      ansible.builtin.file:
        path: "{{ xdg_config_home }}/{{ item }}"
        state: touch
        mode: u+x
        modification_time: preserve
        access_time: preserve
      with_items:
        - i3/close-window.sh
        - i3/power-menu.sh
        - polybar/launch.sh
        - polybar/scripts/bluetoothctl.sh
        - polybar/scripts/keyboardctl.sh

    - name: Copy xinit config
      ansible.builtin.copy:
        src: xinit/xinit
        dest: "{{ ansible_user_dir }}/.xinit"
