---
- name: Fail if OS is not Debian or Ubuntu
  fail:
    msg: This is not Debian or Ubuntu.
  when: ansible_distribution != 'Debian' and ansible_distribution != 'Ubuntu'

- name: Fail if user is root
  fail:
    msg: Please run as normal user.
  when: ansible_user_id == "root"

- import_tasks: apt.yml
- import_tasks: ansible.yml
- import_tasks: user.yml
- import_tasks: firefox.yml
- import_tasks: fonts.yml
- import_tasks: i3.yml
- import_tasks: alacritty.yml
- import_tasks: zsh.yml
- import_tasks: neovim.yml
- import_tasks: obsidian.yml
- import_tasks: rust.yml
- import_tasks: syncthing.yml
- import_tasks: thunderbird.yml
- import_tasks: vscode.yml
