- name: Fail if OS is not Debian or Ubuntu
  ansible.builtin.fail:
    msg: This is not Debian or Ubuntu.
  when: ansible_distribution != 'Debian' and ansible_distribution != 'Ubuntu'

- name: Fail if user is root
  ansible.builtin.fail:
    msg: Please run as normal user.
  when: ansible_user_id == "root"

- name: Setup APT packages
  ansible.builtin.import_tasks: apt.yml
- name: Setup Snap packages
  ansible.builtin.import_tasks: snap.yml
- name: Setup Ansible
  ansible.builtin.import_tasks: ansible.yml
- name: Setup user account
  ansible.builtin.import_tasks: user.yml
- name: Setup configuration files
  ansible.builtin.import_tasks: config.yml
- name: Setup Firefox
  ansible.builtin.import_tasks: firefox.yml
- name: Setup fonts
  ansible.builtin.import_tasks: fonts.yml
- name: Setup Git
  ansible.builtin.import_tasks: git.yml
- name: Setup i3 window manager
  ansible.builtin.import_tasks: i3.yml
- name: Setup Zsh shell
  ansible.builtin.import_tasks: zsh.yml
- name: Setup Neovim
  ansible.builtin.import_tasks: neovim.yml
- name: Setup Rust toolchain
  ansible.builtin.import_tasks: rust.yml
- name: Setup Thunderbird
  ansible.builtin.import_tasks: thunderbird.yml
- name: Setup Claude Code CLI
  ansible.builtin.import_tasks: claude.yml
  when: setup_claude_code | default(true)
- name: Setup Agent-OS
  ansible.builtin.import_tasks: agent-os.yml
  when: setup_agent_os | default(true)
