- name: Rust toolchain installation
  vars:
    rustup_file: "{{ ansible_user_dir }}/.cargo/bin/rustup"
  block:
    - name: Install curl from apt
      ansible.builtin.apt:
        name: curl
      become: true

    - name: Download rustup installer
      ansible.builtin.get_url:
        url: https://sh.rustup.rs
        dest: /tmp/rustup-installer.sh
        mode: '0755'

    - name: Install rust toolchain
      ansible.builtin.command:
        cmd: /tmp/rustup-installer.sh --no-modify-path -y
        creates: "{{ rustup_file }}"

    - name: Update rust toolchain
      ansible.builtin.command: "{{ rustup_file }} update"
      register: rustup_update
      changed_when: "'updated' in rustup_update.stdout"
