- name: Install packages from snap
  community.general.snap:
    name: "{{ item.name }}"
    classic: true
    channel: "{{ item.channel }}"
  become: true
  with_items: "{{ snap_packages }}"

- name: Install screen dependent packages from snap
  community.general.snap:
    name: "{{ item.name }}"
    classic: true
    channel: "{{ item.channel }}"
  become: true
  when: ansible_env.DISPLAY is defined
  with_items: "{{ snap_screen_packages }}"
