---
- name: If run in X.org
  when: ansible_env.DISPLAY is defined
  vars:
    thunderbird_basedir: "{{ ansible_user_dir }}/snap/thunderbird/common/.thunderbird"
    thunderbird_profile_paths: "{{ lookup('file', thunderbird_basedir ~ '/profiles.ini') | regex_findall('^Path=(.*\\.' ~ thunderbird_profiles | join('|.*\\.') ~
      ')$', multiline=True) }}"
  block:
    - name: Install Thunderbird
      ansible.builtin.apt:
        name: thunderbird
      become: true

    - name: Set Thunderbird as default mail manager
      ansible.builtin.command: xdg-settings set default-url-scheme-handler mailto thunderbird.desktop
      failed_when: false
      changed_when: false

    - name: Create Thunderbird profiles
      ansible.builtin.command: thunderbird -CreateProfile "{{ item }}"
      changed_when: false
      with_items: "{{ thunderbird_profiles }}"

    - name: Set Thunderbird to manually choose profile when starting
      ansible.builtin.lineinfile:
        path: "{{ thunderbird_basedir }}/profiles.ini"
        regexp: ^StartWithLastProfile=
        line: StartWithLastProfile=0

    - name: Copy the Thunderbird preferences
      ansible.builtin.copy:
        src: "thunderbird/prefs.js"
        dest: "{{ thunderbird_basedir }}/{{ item }}/prefs.js"
      with_items: "{{ thunderbird_profile_paths }}"

    - name: Create Thunderbird extensions directory
      ansible.builtin.file:
        path: "{{ thunderbird_basedir }}/{{ item }}/extensions"
        state: directory
      with_items: "{{ thunderbird_profile_paths }}"

    - name: Download Thunderbird addons
      ansible.builtin.get_url:
        url: https://addons.thunderbird.net/thunderbird/downloads/latest/{{ item[1] }}/
        dest: "{{ thunderbird_basedir }}/{{ item[0] }}/extensions/"
      loop_control:
        label: "{{ item[0] }} {{ item[1] }}"
      with_nested:
        - "{{ thunderbird_profile_paths }}"
        - "{{ thunderbird_addons }}"
