---
- name: If run in X.org
  block:
    - name: Install Visual Studio Code
      snap:
        name: code
        classic: true
        state: present
      become: true

  when: ansible_env.DISPLAY is defined
